//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::message_table::Entity as MessageTable;
pub use super::participant_table::Entity as ParticipantTable;
pub use super::room_table::Entity as RoomTable;
