//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "room_table")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub room_name: String,
    pub created_time: Option<DateTime>,
    pub updated_time: Option<DateTime>,
    pub room_token: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
